g++ -o test  -I D:\MinGW\include\c++\11.2.0\boost -I D:\MinGW\include\c++\11.2.0\eigen3 .\test.cpp


g++ -std=c++11 -o test  -I /data/software/HiC/vscode_package/boost_1_79_0 -I /data/software/HiC/vscode_package/eigen-3.4.0  ./main.cpp  -pthread
g++ -std=c++11 -o test  ./main.cpp  -pthread
./test
